### 异常

- `java.lang.Throwable`类是Java语言中所有错误或异常的超类

- Exception：编译器异常，进行编译（写代码）java程序出现的问题

- RuntimeException：运行期异常，Java程序运行过程中出现的问题

- jvm检测出程序出现异常，jvm会做两件事
  1. jvm会根据异常产生的原因创建一个异常对象，这个异常对象包含了异常产生的内容/位置/原因
  2. 在对应的方法中，如果没有处理逻辑（try...catch），那么jvm就会把异常对象抛出给方法的调用者main方法来处理这个问题
  
- 如果main方法接收到了这个异常对象，也没有异常得处理逻辑，继续把对象抛出给main方法的调用者jvm处理这个问题

- jvm接收到了这个异常对象，做了两件事情
  1. 把异常对象的内容/原因/位置，以红色的字体打印在控制台
  2. jvm会终止当前正在执行的java程序->中断处理
  
- throw关键字：

  - 作用：可以使用throw关键字在指定的方法中抛出指定的异常

  - 使用格式：`throw new xxxException("异常产生的原因");`

  - 注意:

    1.  throw关键字必须写在方法的内部

    2. throw关键字后边new的对象必须是Exception或者Exception的子类对象

       1. throw关键字抛出指定的异常对象，我们就必须处理这个异常对象
          1.1 throw关键字后边创建的是RuntimeException或者RuntimeException的子类对象，我们可以不处理，默认交给jvm处理（打印异常对象，中断程序）

          1.2 throw关键字后边创建的是编译异常（写代码的时候报错），我们就必须处理这个异常，要么throws，要么try...catch

  - NullPointerException是一个运行期异常，我们不需要处理，默认交给JVM处理

  - IndexOutOfBoundsException也是一个运行期异常，我们不需要处理，默认交给JVM处理

- throws关键字：异常处理的第一种方式，交给别人处理

  - 作用:：当方法内部抛出异常对象的时候，那么我们就必须处理这个异常对象
    可以使用throws关键字处理异常对象，会把异常对象声明抛出给异常的调用者（自己不处理，交给别人处理），最后交割JVM处理-->中断处理

  - 使用格式： 

    ~~~java
    修饰符 返回值类型 方法名(参数列表) throws AAAException,BBBException...{
        throw new AAAException("产生原因");
        throw new BBBException("产生原因");
    }
    ~~~

  - 注意：
    1. throws关键字必须写在方法声明处
    2. throws关键字后边声明的异常必须是Exception或者是Exception的子类
    3. 方法内部如果抛出多个异常对象，那么throws后边必须声明多个异常，如果抛出的多个异常有子父类关系，那么直接声明父类异常即可
    4. 调用了一个声明抛出异常的方法，我们就必须的处理声明的异常，要么继续使用throws声明抛出，交给方法的调用者处理，最终交给jvm，要么try...catch自己处理异常

- FileNotFoundException、IOException是编译异常，抛出了编译异常，必须处理这个异常

- FileNotFoundException继承IOException

- try...catch异常处理的第二种方式，自己处理异常

  - 格式：

    ~~~java
    try{
        可能产生异常的代码
    }catch(定义一个异常的变量，用来接收try中抛出的异常){
        异常处理逻辑，产生异常对象之后，怎么处理异常对象
         一般在工作中，会把异常的信息记录到一个日志中
    }
    ......
    catch(异常类名 变量名){}
    ~~~

  - 注意：
    1. try中可能会产生多个异常对象，那么就可以使用多个catch来处理这些异常对象
    2. 如果try中产生了异常，那么就会执行catch中的异常处理逻辑，执行完catch中的处理逻辑，继续执行try...catch之后的代码
       如果try中没有产生异常，那么就不会执行catch中异常的处理逻辑，执行完try中的代码，继续执行try...catch之后的代码

- Throwable类中定义了3个处理异常的方法

  1. String getMessage()  返回此throwable的简短描述
  2. String toString() 返回throwable的详细信息字符串
  3. void printStackTrace() JVM打印异常对象，默认此方法，打印的异常信息是最全面的

- 多个异常处理方式：

  1. 多个异常分别处理

  2. 多个异常一次捕获，多次处理

     catch里面定义的异常变量，如果有子父类关系，那么子类的异常必须写在上面

  3. 多个异常一次捕获，一次处理

- 如果finally有return语句，永远返回finally中的结果，避免该情况

  ~~~java
  public class Demo{
      public static void main(String[] args){
          int a = getA();
          System.out.println(a);
      }
      public static int getA(){
          int a = 10;
          try{
              return a;
          }catch(Exception e){
              System.out.println(e);
          }finally{
              // 一定会执行的代码
              a = 100;
              return a;              
          }
      }
  }
  // 以上代码，最后输出的结果是100
  ~~~

- 子父类异常：

  1. 如果父类抛出了多个异常，子类重写方法时，抛出和父类相同的异常或者父类异常的子类或者不抛出异常
  2. 父类方法没有抛出异常，子类重写父类该方法时也不可抛出异常，此时子类产生该异常，只能捕获处理，不能声明抛出

  - 注意：以上两点归纳为：父类异常是什么样，子类异常就什么样

- 自定义异常类：

  - 格式：

    ~~~java
    public class XXXException extends Exception | RuntimeException{
        添加一个空参数构造方法
        添加一个带异常信息的构造方法
    }
    ~~~

  - 注意：
    1. 自定义异常类一般是以Exception结尾，说明该类是一个异常类
    2. 自定义异常类，必须继承Exception或者RuntimeException
       - 继承Exception：那么自定义的异常类就是一个编译器异常，如果方法内部抛出了编译器异常，就必须处理这个异常，要么throws，要么try...catch
       - 继承RuntimeException：那么自定义的异常类就是一个运行期异常，无需处理，交给虚拟机处理（中断处理）

